package mx.openpay.client;

import java.util.Date;

import lombok.Getter;
import lombok.Setter;
import lombok.ToString;

import com.google.gson.annotations.SerializedName;

/**
 * Represents the Bank Account of either a Customer or the Merchant.
 * @author elopez
 */
@Getter
@Setter
@ToString
public class BankAccount {

    /** Identifier. This field is autogenerated by Openpay. */
    private String id;

    /** Name of the bank. This field is filled by Openpay. */
    @SerializedName("bank_name")
    private String bankName;

    /** Name of the bank account's owner. Required. */
    @SerializedName("holder_name")
    private String holderName;

    /** CLABE of the account. Required. */
    private String clabe;

    /** An optional name to assign to the account. Optional. */
    private String alias;

    /** The Bank Code of the account. This field is filled by Openpay. */
    @SerializedName("bank_code")
    private String bankCode;

    /** The date the Bank Account was registered in Openpay. This field is filled by Openpay. */
    @SerializedName("creation_date")
    private Date creationDate;

}
